VIsheshSaluja-Chapters
geo-smart/swe-workflow-book pull request #2
Opened 2024-03-29 01:09 UTC by VisheshSaluja

Two chapters:
Model Testing and validation
Model Prediction and Results

2024-03-30 15:29 UTC, gokulprathin8 requested changes
can you please fix the quality control check and check spellings

2024-04-05 01:30 UTC, gokulprathin8 requested changes
please work on the changes.

2024-04-05 01:30 UTC, gokulprathin8 commented on testing&Evaluation.ipynb
> +{
<img width="649" alt="image" src="https://github.com/geo-smart/swe-workflow-book/assets/45752727/f1f1e4af-16a8-4c2c-9391-2c380a6fb0ff">

please use academic tone.

2024-04-05 01:30 UTC, gokulprathin8 commented on testing&Evaluation.ipynb
> +  "nbformat": 4,
<img width="623" alt="image" src="https://github.com/geo-smart/swe-workflow-book/assets/45752727/60a7c9f7-cfcf-4c03-9489-2239e5994e34">

Please use academic tone.

2024-04-05 01:30 UTC, gokulprathin8 commented on testing&Evaluation.ipynb
> +  "nbformat_minor": 0,
<img width="645" alt="image" src="https://github.com/geo-smart/swe-workflow-book/assets/45752727/91146bda-9351-469c-ab6b-12c5d169b343">

Please use acadmic tone.

2024-04-05 01:30 UTC, gokulprathin8 commented on testing&Evaluation.ipynb
> +    "colab": {
<img width="705" alt="image" src="https://github.com/geo-smart/swe-workflow-book/assets/45752727/c945f24c-cd3e-4fb6-ba3a-be24f1faeb0c">

Can you run the code and commit the notebook with the output log?

2024-04-05 01:30 UTC, gokulprathin8 commented on Prediction_Eval.ipynb
> +{
<img width="646" alt="image" src="https://github.com/geo-smart/swe-workflow-book/assets/45752727/8ff67e3f-8ab9-43f0-829f-b8a1eb6530cc">

please use academic tone.

2024-04-05 01:30 UTC, gokulprathin8 commented on Prediction_Eval.ipynb
> +  "nbformat": 4,
<img width="717" alt="image" src="https://github.com/geo-smart/swe-workflow-book/assets/45752727/fff530fe-9a7b-4180-afef-1e842a567ee9">

Missing code of merge_data and predict

2024-04-05 01:30 UTC, gokulprathin8 commented on Prediction_Eval.ipynb
> +  "nbformat_minor": 0,
<img width="670" alt="image" src="https://github.com/geo-smart/swe-workflow-book/assets/45752727/f24cf99d-dc61-419a-80e1-e0e85ecf0576">

on the prediction, we need to show the output log of the code.

2024-04-05 01:30 UTC, gokulprathin8 commented on Prediction_Eval.ipynb
> +  "metadata": {
<img width="649" alt="image" src="https://github.com/geo-smart/swe-workflow-book/assets/45752727/70524de1-735f-4339-adee-241e64de7ff7">

Please dont use snake case on headings

2024-04-05 01:30 UTC, gokulprathin8 commented on Prediction_Eval.ipynb
> +    "colab": {
<img width="706" alt="image" src="https://github.com/geo-smart/swe-workflow-book/assets/45752727/5757fb54-569a-49a7-8293-4c6437d29ff7">

please run this and it needs the output image map.

2024-04-05 01:30 UTC, gokulprathin8 commented on Prediction_Eval.ipynb
> +    "colab": {
results is the most important section of the book. please elaborate more with the generated image.

2024-04-05 01:30 UTC, gokulprathin8 commented on Prediction_Eval.ipynb
> +      "provenance": []
<img width="668" alt="image" src="https://github.com/geo-smart/swe-workflow-book/assets/45752727/8e3ba0c3-b45b-4a4c-aa21-b4f4ae3ca944">

again, please dont use snake case for headings.

2024-04-10 13:55 UTC, gokulprathin8 commented
is this ready for review? @VisheshSaluja

2024-04-10 13:58 UTC, VisheshSaluja commented
Yes, I was going to put a message on slack
I added a few images, let me know if more are needed
I also changes the language of all the parts you asked me to.

2024-04-14 06:51 UTC, ZihengSun commented on book/chapters/Prediction.ipynb
> +        "Finally, we are at the final Chapter where we see the end-product of the model created. As we venture into this critical phase, the model_predict script emerges as a lighthouse, guiding the
It is not RandomForestHole model. It is the ExtraTree model.

2024-04-14 06:52 UTC, ZihengSun commented on book/chapters/Prediction.ipynb
> +        "Pre-processing: Next, the data undergoes a transformation. Dates are converted, irrelevant columns are discarded, and the data is reshaped to match the model's expectations. This step is aki
Better remove `akin to sharpening the sword before battle`. Feels unnatural here.

2024-04-14 06:53 UTC, ZihengSun commented on book/chapters/Prediction.ipynb
> +        "Pre-processing: Next, the data undergoes a transformation. Dates are converted, irrelevant columns are discarded, and the data is reshaped to match the model's expectations. This step is aki
When you are introducing scientific experiments, better keep it serious and integrate.

2024-04-14 06:54 UTC, ZihengSun commented on book/chapters/Prediction.ipynb
> +        "**Merge data:** The merge_data function plays a crucial role in combining the predicted SWE values with their corresponding geographical markers. Conditional Adjustments: Refines the predict
remove `plays a crucial role in`

2024-04-14 06:55 UTC, ZihengSun commented on book/chapters/Prediction.ipynb
> +        "**Resolution and Coverage:** Carefully defines the resolution and geographical extent of the output map, ensuring that it captures the full scope of the predictions.\n",
Not sure understand what this means. How `carefully` will be enough careful. It is quite vague to read these sentences. Can you be more precise and specific?

2024-04-14 06:55 UTC, ZihengSun commented on book/chapters/validation.ipynb
> +        "In predictive modeling, the objective to forecast Snow Water Equivalent stands as a testament to the confluence of data science and environmental science. This chapter delved into the testin
Remove `In predictive modeling,`

2024-04-14 06:56 UTC, ZihengSun commented on book/chapters/validation.ipynb
> +        "In predictive modeling, the objective to forecast Snow Water Equivalent stands as a testament to the confluence of data science and environmental science. This chapter delved into the testin
`the objective to forecast Snow Water Equivalent stands as a testament to the confluence of data science and environmental science.` reads awkward and not sure what it is driving at.

2024-04-14 06:56 UTC, ZihengSun commented on book/chapters/validation.ipynb
> +        "But first BaseHole is an important part to understand. The BaseHole class embodies the lifecycle of machine learning in this project, from inception to deployment."
can you rewrite? make it more readable and understandable?

2024-04-14 06:57 UTC, ZihengSun commented on book/chapters/validation.ipynb
> +        "At the heart of Snowcast's predictive prowess lies the BaseHole class -- a meticulously crafted blueprint for constructing models capable of predicting SWE. This class serves as the cornerst
Can you rewrite? if using AI, please at least read them first and make sure they are smoothly transitioned.

2024-04-14 06:58 UTC, ZihengSun requested changes
Added some comments. Some paragraphs read very awkward and they are completely off the topic or just irrelevant and no idea where they are driving to. Please adjust your prompts and make sure all the paragraphs make sense, self explainable and understandable.

2024-04-14 13:57 UTC, VisheshSaluja commented
Will make the changes @ZihengSun

2024-05-16 15:23 UTC, ZihengSun approved these changes
LG, although we need to add the live output for each function with small subset test data in next PR.

2024-05-16 17:46 UTC, merged