Initial Commit to AMSR
geo-smart/swe-workflow-book pull request #4
Opened 2024-03-29 19:38 UTC by srilathamaddineni

2024-04-02 04:09 UTC, ZihengSun commented on book/chapters/amsr.ipynb
> +    "    save_location = \"C:/Users/srila/gridmet_test_run/amsr\"\n",
You shouldn't use your personal directory path in any of the notebooks. Please change it to relative path and make sure it works on all people's laptops.

2024-04-02 04:09 UTC, ZihengSun requested changes
Please see my comments.

2024-04-05 04:35 UTC, saivivek116 commented
- The headings need to be more explanative currently the headings are function names instead you can give meaningful headings

- As there are several functions in this chapter(divide into sub chapters if needed) its better you try to make it more engaging with headings, explanations and graphs 

- explanation of the code inside function and the purpose of the function can be separated( into different paragraphs) divide the larger function into chunks

- give conclusion of the chapter

- remove unused code

- Once the paths are modified and respective files needed to execute the notebook will verify further

2024-04-05 04:38 UTC, saivivek116 requested changes
pls check my comments.

2024-05-19 19:42 UTC, ZihengSun commented
@saivivek116 please help with this PR by directly contributing to the content.

2024-05-27 16:06 UTC, ZihengSun approved these changes
I am going to merge this PR. @saivivek116 please correct the two left issues in separate PRs.

2024-05-27 16:06 UTC, merged