Changes to fSCA and SNOTEl
geo-smart/swe-workflow-book pull request #6
Opened 2024-03-30 16:16 UTC by manasa123104

2024-03-30 16:20 UTC, gokulprathin8 commented
please merge fSCA training and testing into a single chapter

2024-04-02 00:08 UTC, saivivek116 commented
can you pls check the markdown of the headings
there is not separation between heading and its contents 
use bold text for headings and use : or new line for seperation
for markdown stylings
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
refer this 
and review your changes in the preview

2024-04-02 00:19 UTC, saivivek116 commented
No Code related to fSCA training, fSCA testing and data_snotel_stations process nodes in the books.
can you pls add Code and its explanation for the better understanding.

2024-04-02 04:11 UTC, ZihengSun commented on book/chapters/fsCA.ipynb
> +    "accuracies = [82, 85, 92, 90]\n",
What do these numbers come from? It feels disrupted coming out from nowhere.

2024-04-02 04:12 UTC, ZihengSun requested changes
The markdown is very messy. Please correct. Also, get the chapter logic together. It doesn't make any sense right now.

2024-04-04 00:56 UTC, gokulprathin8 commented
snotel review:
[snotel.pdf](https://github.com/geo-smart/swe-workflow-book/files/14860012/snotel.pdf)

2024-04-04 01:34 UTC, gokulprathin8 commented
fSCA review:
[fsCA.pdf](https://github.com/geo-smart/swe-workflow-book/files/14860228/fsCA.pdf)

2024-05-19 19:41 UTC, ZihengSun commented
probably shouldn't remove the three data files.

2024-08-15 23:55 UTC, closed without merging